export const metadata = {
    title: "NyAsociados - Nosotros",
    description: "Generated by create next app",
    icons: {
      icon: '/logo_dark.png',
    },
  };
export default function Nosotros(){
    return(
        <h1>
            q wea ctmre queri morir
        </h1>
    )
}